joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

camera_controller:
  type: "position_controllers/JointPositionController"
  joint: base_to_camera

front_left_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: base_to_front_left_wheel

front_right_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: base_to_front_right_wheel

back_left_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: base_to_back_left_wheel

back_right_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: base_to_back_right_wheel



